#pragma comment(linker, "/stack:200000000")
#pragma GCC optimize("Ofast")
#pragma GCC optimize("unroll-loops")
#pragma GCC optimize("-O3")
#pragma GCC optimize("fast-math")
#pragma GCC optimize("no-stack-protector")
#pragma GCC target("avx2,bmi,bmi2,lzcnt,sse,sse2,sse3,ssse3,sse4,popcnt,abm,mmx,avx,tune=native")